[tool.poetry]
name = "testpy"
version = "0.1.0"
description = "Im Trying"
authors = ["yuja2@alumni.vcu.edu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
